export function About() {
  return (
    <div class="container">
      <h1> About This Site (and me!) </h1>
      <br></br>
      <h4>
        My name is Liat Hirsh. I am a software developer with a passion for
        creating tools that make people's lives easier. I believe that the power
        of technology lies in its ability to simplify and streamline complex
        processes, and that's exactly what I aim to do with my work.
      </h4>
      <br></br>
      <h4>
        I believe that the Python ecosystem is one of the richest and most
        diverse of any programming language, and I am excited to be able to
        provide a platform for users to discover and explore the amazing
        packages that make it so powerful.{" "}
      </h4>
      <br></br>
      <h4>
        {" "}
        You can contribute to this project by voting on the Python packages you
        work with and prefer. Making it easier for newer developers to know
        where to begin when starting a project. My latest project is a website
        dedicated to showcasing the best and most popular Python packages.{" "}
      </h4>
      <br></br>
      <h4>
        The site is built with React JS on the front-end and a Flask backend,
        with a PostgreSQL database to store user votes and package information.{" "}
      </h4>
      <br></br>
      <h4>
        I hope that this website will be a valuable resource for both
        experienced and new developers alike, and I look forward to hearing your
        feedback and suggestions.{" "}
      </h4>
      <br></br>
      <h3> Thank you for visiting, and happy coding! </h3>
      <br></br>

      <p>
        {" "}
        The text for each package and category on this website was generated by
        ChatGPT
      </p>
    </div>
  );
}
